# Generated by Django 4.0.5 on 2022-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_core_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=11)),
            ],
        ),
    ]
