# Generated by Django 4.0.5 on 2023-01-21 15:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_about',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='core_home',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
