# Generated by Django 4.0.5 on 2023-01-09 14:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_homemodel_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='paragraph',
            field=tinymce.models.HTMLField(),
        ),
    ]
