# Generated by Django 4.0.5 on 2023-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_formmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
