# Generated by Django 4.0.5 on 2023-01-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_skillsmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodel',
            name='value',
            field=models.IntegerField(verbose_name='max_value=100'),
        ),
    ]
