# Generated by Django 4.0.5 on 2023-01-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_alter_skillsmodel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='colour',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
