# Generated by Django 4.0.5 on 2023-01-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_skillsmodel_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsmodel',
            old_name='colour',
            new_name='color',
        ),
    ]
