# Generated by Django 4.0.5 on 2023-01-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servmodel',
            old_name='paragraph',
            new_name='desc',
        ),
    ]
