# Generated by Django 4.0.5 on 2023-01-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0002_rename_paragraph_servmodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servmodel',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
